/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bio.views;
import bio.api.GetEmployee;
import bio.models.Authentification;
import bio.models.Collaborateur;
import bio.models.Empreinte;
import bio.models.Rajout;
import bio.models.Adresse;
import bio.models.Identification;
import bio.models.AuthUser;
import bio.models.Ident;
import dao.factory.DAOFactory;
import eu.hansolo.steelseries.gauges.Linear;
import eu.hansolo.steelseries.tools.ColorDef;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.util.Date;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import zkfinger.FingerThread;
import zkfinger.TrackThread;
import zkfinger.ZKScanner;
import zkfinger.ZKScannerMatch;

/**
 *
 * @author HP
 */
public class MainMenu extends javax.swing.JFrame {
     private int selectedRows;
    private int fingerPrintItem;
   /* private MyThread thread;*/
    public Linear gauge;
    public boolean stop = false;
    private boolean isIdent = false;
    public JLabel labIcon;
    private static MainMenu instance;
    private TrackThread tThread;
    private Collaborateur collab;
    private String cname;
    private String cmatr;
    private String cdate;
    private String ctype;
    /**
     * Creates new form MainMenu
     */
    public MainMenu getInstance(){
        if(instance == null){
            instance  = new MainMenu();
        } else{
            instance.init();
        }
        
        return instance;
    }
    public MainMenu() {
        initComponents();
        this.gauge = new Linear();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.gauge.setValueAnimated(0.0D);
        this.gauge.setTitle("Correspondance");
        this.gauge.setGlowVisible(true);
        this.gauge.setGlowing(true);
        this.labIcon= this.labmatchfp;
        this.gaugePanel.setLayout(new BorderLayout());
        this.gaugePanel.setPreferredSize(new Dimension(475,150));
        this.gaugePanel.add(this.gauge, BorderLayout.CENTER);
        this.goCheck();
    }
    
    public void init(){
        this.tThread = new TrackThread();
        this.goCheck();
    }
    
    public void initializeAll(){
        this.selectedRows = -1;
        this.fingerPrintItem = 1;
        this.labfingerone.setText("");
        this.labanotherfinger.setText("");
        this.libanotherfinger.setIcon(null);
        this.libfingerone.setIcon(null);
    }
    public void goCheck(){
        stop = false;
        TrackThread tThread = new TrackThread();
        tThread.setMatr("101703");
        tThread.setLibContent(this.labmatchfp);
        tThread.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menubar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labident = new javax.swing.JLabel();
        labenreg = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        panIdentification = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panEmpreintedigit = new javax.swing.JPanel();
        labmatchfp = new javax.swing.JLabel();
        panIdentInfo = new javax.swing.JPanel();
        gaugePanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labmatchtypat = new javax.swing.JLabel();
        labmatchdatenaiss = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labmatchname = new javax.swing.JLabel();
        panEnregistrement = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panCollabs = new javax.swing.JPanel();
        matriculeField = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panInfoCollabs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        datenaiss = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        typepat = new javax.swing.JLabel();
        panEmpreinte = new javax.swing.JPanel();
        choixEmpreinte = new javax.swing.JPanel();
        selectFinger = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        enregButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        libanotherfinger = new javax.swing.JLabel();
        labanotherfinger = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        libfingerone = new javax.swing.JLabel();
        labfingerone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1370, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(60, 141, 188));
        nav.setPreferredSize(new java.awt.Dimension(1370, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CMS BIOMETRIC");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel6.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel6.setPreferredSize(new java.awt.Dimension(34, 34));
        jLabel6.setRequestFocusEnabled(false);

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1181, Short.MAX_VALUE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menubar.setBackground(new java.awt.Color(34, 45, 49));

        jPanel2.setBackground(new java.awt.Color(34, 45, 49));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 153, 153)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RAHANARISON Jules");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ENREGISTREMENT");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(34, 45, 49));
        jButton1.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("IDENTIFICATION");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labident.setBackground(new java.awt.Color(255, 102, 0));
        labident.setOpaque(true);

        labenreg.setBackground(new java.awt.Color(34, 45, 49));
        labenreg.setOpaque(true);

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menubarLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(labident, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labenreg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menubarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(695, 695, 695))))
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubarLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labident, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE)
                    .addComponent(labenreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 80));

        container.setLayout(new java.awt.CardLayout());

        panEmpreintedigit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panEmpreintedigitLayout = new javax.swing.GroupLayout(panEmpreintedigit);
        panEmpreintedigit.setLayout(panEmpreintedigitLayout);
        panEmpreintedigitLayout.setHorizontalGroup(
            panEmpreintedigitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmpreintedigitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labmatchfp, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        panEmpreintedigitLayout.setVerticalGroup(
            panEmpreintedigitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmpreintedigitLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labmatchfp, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panIdentInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        gaugePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout gaugePanelLayout = new javax.swing.GroupLayout(gaugePanel);
        gaugePanel.setLayout(gaugePanelLayout);
        gaugePanelLayout.setHorizontalGroup(
            gaugePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gaugePanelLayout.setVerticalGroup(
            gaugePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setText("Correspondance");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setText("Date de naissance:");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Type patient:");

        labmatchname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labmatchdatenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labmatchtypat, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labmatchname, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labmatchname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labmatchdatenaiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labmatchtypat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panIdentInfoLayout = new javax.swing.GroupLayout(panIdentInfo);
        panIdentInfo.setLayout(panIdentInfoLayout);
        panIdentInfoLayout.setHorizontalGroup(
            panIdentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIdentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panIdentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gaugePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panIdentInfoLayout.setVerticalGroup(
            panIdentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panIdentInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gaugePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panEmpreintedigit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panIdentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panEmpreintedigit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panIdentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panIdentificationLayout = new javax.swing.GroupLayout(panIdentification);
        panIdentification.setLayout(panIdentificationLayout);
        panIdentificationLayout.setHorizontalGroup(
            panIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIdentificationLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        panIdentificationLayout.setVerticalGroup(
            panIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIdentificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        container.add(panIdentification, "card3");

        jPanel3.setMaximumSize(new java.awt.Dimension(1370, 730));
        jPanel3.setMinimumSize(new java.awt.Dimension(1370, 730));
        jPanel3.setPreferredSize(new java.awt.Dimension(1370, 730));

        panCollabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        try {
            matriculeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOM", "TYPE PATIENT", "DATE DE NAISSANCE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panCollabsLayout = new javax.swing.GroupLayout(panCollabs);
        panCollabs.setLayout(panCollabsLayout);
        panCollabsLayout.setHorizontalGroup(
            panCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCollabsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(matriculeField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(panCollabsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panCollabsLayout.setVerticalGroup(
            panCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCollabsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(matriculeField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
        );

        panInfoCollabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("INFORMATIONS");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("TYPE PATIENT          :");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("NOM                          :");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("DATE DE NAISSANCE : ");

        javax.swing.GroupLayout panInfoCollabsLayout = new javax.swing.GroupLayout(panInfoCollabs);
        panInfoCollabs.setLayout(panInfoCollabsLayout);
        panInfoCollabsLayout.setHorizontalGroup(
            panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoCollabsLayout.createSequentialGroup()
                .addGroup(panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInfoCollabsLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panInfoCollabsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typepat, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panInfoCollabsLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(467, Short.MAX_VALUE)))
        );
        panInfoCollabsLayout.setVerticalGroup(
            panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoCollabsLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typepat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(panInfoCollabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panInfoCollabsLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );

        panEmpreinte.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        choixEmpreinte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPREINTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 2, 14))); // NOI18N

        selectFinger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner", "Pouce D", "Pouce G", "Index D", "Index G", "Majeur D", "Majeur G", "Annuaire D", "Annuaire G", "Auriculaire D", "Auriculaire G" }));
        selectFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFingerActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        enregButton.setBackground(new java.awt.Color(255, 153, 0));
        enregButton.setText("ENREGISTRER");
        enregButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.setActionCommand("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enregButton, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enregButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout choixEmpreinteLayout = new javax.swing.GroupLayout(choixEmpreinte);
        choixEmpreinte.setLayout(choixEmpreinteLayout);
        choixEmpreinteLayout.setHorizontalGroup(
            choixEmpreinteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choixEmpreinteLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(choixEmpreinteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectFinger, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        choixEmpreinteLayout.setVerticalGroup(
            choixEmpreinteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choixEmpreinteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectFinger, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        libanotherfinger.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(libanotherfinger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labanotherfinger, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(labanotherfinger, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libanotherfinger, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        libfingerone.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(libfingerone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(labfingerone, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labfingerone, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libfingerone, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panEmpreinteLayout = new javax.swing.GroupLayout(panEmpreinte);
        panEmpreinte.setLayout(panEmpreinteLayout);
        panEmpreinteLayout.setHorizontalGroup(
            panEmpreinteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmpreinteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choixEmpreinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panEmpreinteLayout.setVerticalGroup(
            panEmpreinteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmpreinteLayout.createSequentialGroup()
                .addGroup(panEmpreinteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panEmpreinteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(choixEmpreinte, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panEmpreinte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panCollabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panInfoCollabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panInfoCollabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCollabs, javax.swing.GroupLayout.PREFERRED_SIZE, 227, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panEmpreinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panEnregistrementLayout = new javax.swing.GroupLayout(panEnregistrement);
        panEnregistrement.setLayout(panEnregistrementLayout);
        panEnregistrementLayout.setHorizontalGroup(
            panEnregistrementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEnregistrementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panEnregistrementLayout.setVerticalGroup(
            panEnregistrementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEnregistrementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.add(panEnregistrement, "card2");

        jPanel1.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1370, 590));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        labenreg.setBackground(new Color(255,102,0));
        labident.setBackground(new Color(34,45,49));
        container.removeAll();
        container.repaint();
        container.revalidate();
        container.add(panEnregistrement);
        container.repaint();
        container.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        labident.setBackground(new Color(255,102,0));
        labenreg.setBackground(new Color(34,45,49));
        container.removeAll();
        container.repaint();
        container.revalidate();
        container.add(panIdentification);
        container.repaint();
        container.revalidate();
        this.goCheck();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.initializeAll();
        this.setDataTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row= this.jTable1.getSelectedRow();
        this.setValueSelectedRows(row);
    }//GEN-LAST:event_jTable1MouseClicked

    private void enregButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregButtonActionPerformed
        // TODO add your handling code here:
        if(this.libfingerone.getIcon()==null){
            JOptionPane.showMessageDialog(this, "Veuillez scanner votre empreinte avant d'enregistrer! ", "Message", 2);
        } else if( this.libanotherfinger.getIcon() == null){
            JOptionPane.showMessageDialog(this, "Vauillez scanner votre empreinte avant d'enregistrer! ", "Message", 2);
        } else{
            /*collab =*/ 
          
            Collaborateur newCollaborateur = new Collaborateur(this.cmatr, this.cname, this.cdate, this.ctype);
            Collaborateur use = DAOFactory.getCollaborateurDAO().isthere(newCollaborateur);
            if (use == null) {
                DAOFactory.getCollaborateurDAO().create(newCollaborateur);
            } else {
                newCollaborateur = use;
                System.out.println(newCollaborateur.getId());
            } 
            collab = DAOFactory.getCollaborateurDAO().get(newCollaborateur.getId());
            if ( collab != null){
               List<Empreinte> checkEmp = DAOFactory.getEmpreinteDAO().getAllById(collab.getId());
               if(checkEmp.isEmpty()){
                   Empreinte empreinte1 = DAOFactory.getEmpreinteDAO().create(new Empreinte(this.labfingerone.getText(), collab.getId()));
                   Empreinte empreinte2 = DAOFactory.getEmpreinteDAO().create(new Empreinte(this.labanotherfinger.getText(), collab.getId()));
                   Rajout objR = new Rajout(empreinte1.getId(),Authentification.getSession().getId(),0, "inscription");
                   Rajout objR2 = new Rajout(empreinte2.getId(), Authentification.getSession().getId(), 0, "inscription");
                   // (new RajoutDAO()).create(objR);
                   DAOFactory.getRajoutDAO().create(objR);
                   DAOFactory.getRajoutDAO().create(objR2);
                   JOptionPane.showMessageDialog(this,"Empreintes ajoutés avec succès");
                   this.initializeAll();
               } else{
                   
                   DAOFactory.getEmpreinteDAO().deleteById(collab.getId());
                   Empreinte empreinte1 = DAOFactory.getEmpreinteDAO().create(new Empreinte(this.labfingerone.getText(), collab.getId()));
                   Empreinte empreinte2 = DAOFactory.getEmpreinteDAO().create(new Empreinte(this.labanotherfinger.getText(), collab.getId()));
                  // Rajout objR = new Rajout(empreinte1.getId(),Authentification.getSession().getId(),0, "inscription");
                   // Rajout objR2 = new Rajout(empreinte2.getId(), Authentification.getSession().getId(), 0, "inscription");
                   //DAOFactory.getRajoutDAO().create(objR);
                   //DAOFactory.getRajoutDAO().create(objR2);
                   for(Empreinte emp : checkEmp){
                       Rajout objR = DAOFactory.getRajoutDAO().get(emp.getId());
                       boolean del = DAOFactory.getRajoutDAO().delete(objR);
                   }
                   Rajout objR = new Rajout(empreinte1.getId(),Authentification.getSession().getId(),0, "inscription");
                   Rajout objR2 = new Rajout(empreinte2.getId(), Authentification.getSession().getId(), 0, "inscription");
                   DAOFactory.getRajoutDAO().create(objR);
                   DAOFactory.getRajoutDAO().create(objR2);
                   JOptionPane.showMessageDialog(this,"Empreintes modifiés avec succès");
               }
               
               //System.out.prinn(Authentification.getSession().getId());
            } else{
                JOptionPane.showMessageDialog(this, "Veuillez selectionner une personne");
            }
        }
    }//GEN-LAST:event_enregButtonActionPerformed

    private void selectFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFingerActionPerformed
        if(this.fingerPrintItem >1){
            this.fingerPrintItem = 1;
        }
        else{
            this.fingerPrintItem++ ;
        }
        this.doAction(selectFinger.getSelectedItem().toString());
    }//GEN-LAST:event_selectFingerActionPerformed
    public void setDataTable(){
        if(this.matriculeField.isValid()){
            List<Collaborateur> ayants =  GetEmployee.GetEmplArray(this.matriculeField.getText());
            String[] columns = {"NOM", "TYPE PATIENT", "DATE DE NAISSANCE"};
            ArrayList<List> listAyants = new ArrayList<>();
            DefaultTableModel tbModel = new DefaultTableModel(columns,0);
            for(Collaborateur c : ayants){
              Object[] list = {c.getName(),c.getType(),c.getDateNaiss()};   
              tbModel.addRow(list);
            }

            this.jTable1.setModel(tbModel);
     }
     else{
         JOptionPane.showMessageDialog(this, "Matricule non valide");
     
        }
    
    }
    public void doAction(String finger){
        FingerThread mThread = new FingerThread();
        String matr= this.matriculeField.getText();
        mThread.setFinger(finger);
        mThread.setMatr(matr);
        mThread.setTypat(this.jTable1.getValueAt(this.selectedRows, 1).toString());
        if(this.fingerPrintItem == 2){
            mThread.setLibContent(this.libfingerone);
            this.labfingerone.setText(this.selectFinger.getSelectedItem().toString());
            
        }
        else{
            mThread.setLibContent(this.libanotherfinger);
            
            this.labanotherfinger.setText(this.selectFinger.getSelectedItem().toString());
        }
        mThread.start();
    }
    
    private void setValueSelectedRows(int val){
        this.selectedRows = val;
        this.name.setText(this.jTable1.getValueAt(val, 0).toString());
        this.datenaiss.setText(this.jTable1.getValueAt(val, 2).toString());
        this.typepat.setText(this.jTable1.getValueAt(val, 1).toString());
        
        /* define current collab */
        this.cname = this.jTable1.getValueAt(val, 0).toString();
        this.cmatr = this.matriculeField.getText();
        this.cdate = this.jTable1.getValueAt(val, 2).toString();
        this.ctype = this.jTable1.getValueAt(val, 1).toString();
    }
   
   
    public class TrackThread extends Thread{
    private String matr;
 
    public void setMatr(String matricule) {
        this.matr = matricule;
    }

    public String getMatr() {
        return matr;
    }
    
    
    private boolean isCapture = false; 

    public boolean isIsCapture() {
        return isCapture;
    }
    
    public void run() { 
    while(true){
        try {
            this.isCapture = ZKScanner.getInstance().capture();
            System.out.println(this.isCapture);
            if(this.isCapture){
               this.setImageIcon();
               ZKScannerMatch match= ZKScanner.getInstance().match();
                
              /* try {
                   BufferedImage image = ImageIO.read(new File("fingerprint.bmp"));
                   ByteArrayOutputStream fingerByte = new ByteArrayOutputStream();
                   ImageIO.write(image, "jpg", fingerByte);
                   byte[] jpgByteArray = fingerByte.toByteArray();
                   
                   StringBuilder sb= new StringBuilder();
                   for(byte by: jpgByteArray){
                       sb.append(Integer.toBinaryString(by & 0xFF));
                       System.out.println(sb.toString());
                   }
               }
               catch(IOException ex){
                   System.out.println("Error");
               }*/
               if(match.score < 50){
                   System.out.println("Ligne 980: Tonga eto");
                    MainMenu.this.gauge.setValueColor(ColorDef.RED);
                    MainMenu.this.gauge.setValueAnimated(match.score);
                    
               } else if(match.score < 80){
                   System.out.println("Ligne 985: Tonga eto");
                   MainMenu.this.gauge.setValueColor(ColorDef.YELLOW);
                   MainMenu.this.gauge.setValueAnimated(match.score);
                   System.out.println(match.score);
                   MainMenu.this.collab= DAOFactory.getCollaborateurDAO().get(match.empreinte.getCollaborateur_id());
                   MainMenu.this.gauge.setTitle(MainMenu.this.collab.getName());
                   MainMenu.this.labmatchname.setText(MainMenu.this.collab.getName());
                   MainMenu.this.labmatchdatenaiss.setText(MainMenu.this.collab.getDateNaiss());
                   MainMenu.this.labmatchtypat.setText(MainMenu.this.collab.getType());
                   Rajout objR = new Rajout(match.empreinte.getId(), Authentification.getSession().getId(), match.score, "identification");
                   DAOFactory.getRajoutDAO().create(objR);
                   /*int indexmax =  DAOFactory.getIdentificationDAO().getMAxTableIdentification();
                   if(indexmax == 0){
                       DAOFactory.getIdentificationDAO().create_identification(, String.valueOf(match.score));
                   }
                   List<Identification> farany = DAOFactory.getIdentificationDAO().getAllTableIdentification(indexmax);
   
                   DAOFactory.getIdentificationDAO().create_identification(farany.get(0), String.valueOf(match.score));*/
            
                   DAOFactory.getRajoutDAO().create(objR);
                   Collaborateur col = MainMenu.this.collab;
                   String colmatr = MainMenu.this.collab.getMatricule();
                   int matr = Integer.parseInt(colmatr);
                   AuthUser authuser =  AuthUser.getAuthUser();
                   Authentification auth = Authentification.getSession();
                   Empreinte emp = match.empreinte;
                   int adresse_d= Authentification.getSession().getAdresse_id();
                   Adresse adr= DAOFactory.getAdresseDao().get(adresse_d); 
                   Date date = new Date();
                   SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss") ;
                   String currentDateTime = format.format(date);
                   DAOFactory.getIdentDAO().create(new Ident(authuser.getAdresseId(),auth.getId(), emp.getId(), authuser.getUsername(), match.score, emp.getFinger(), emp.getCollaborateur_id(), authuser.getCodecms(),matr, currentDateTime));
               } else{
                   MainMenu.this.gauge.setValueColor(ColorDef.GREEN);
                   System.out.println("Ligne 963: Tonga eto");
                   MainMenu.this.gauge.setValueAnimated(match.score);
                   System.out.println(match.score);
                   MainMenu.this.collab= DAOFactory.getCollaborateurDAO().get(match.empreinte.getCollaborateur_id());
                   MainMenu.this.gauge.setTitle(MainMenu.this.collab.getName());
                   MainMenu.this.labmatchname.setText(MainMenu.this.collab.getName());
                   MainMenu.this.labmatchdatenaiss.setText(MainMenu.this.collab.getDateNaiss());
                   MainMenu.this.labmatchtypat.setText(MainMenu.this.collab.getType());
                   Rajout objR = new Rajout(match.empreinte.getId(), Authentification.getSession().getId(), match.score, "identification");
                   DAOFactory.getRajoutDAO().create(objR);
                   Collaborateur col = MainMenu.this.collab;
                   String colmatr = MainMenu.this.collab.getMatricule();
                   int matr = Integer.parseInt(colmatr);
                   AuthUser authuser =  AuthUser.getAuthUser();
                   Authentification auth = Authentification.getSession();
                   Empreinte emp = match.empreinte;
                   int adresse_d= Authentification.getSession().getAdresse_id();
                   Adresse adr= DAOFactory.getAdresseDao().get(adresse_d); 
                   Date date = new Date();
                   SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss") ;
                   String currentDateTime = format.format(date);
                   DAOFactory.getIdentDAO().create(new Ident(authuser.getAdresseId(),auth.getId(), emp.getId(), authuser.getUsername(), match.score, emp.getFinger(), emp.getCollaborateur_id(), authuser.getCodecms(),matr, currentDateTime));
               }
               
            }
            Thread.sleep(500);
         } catch (InterruptedException ie) {
          ie.printStackTrace();
        }
    }
  }
    
    private JLabel libContent;

    public void setLibContent(JLabel libContent) {
        this.libContent = libContent;
    }
 
 public void setImageIcon(){
        try {
            this.libContent.setText("");
            InputStream is = new BufferedInputStream(new FileInputStream("fingerprint.bmp"));
            BufferedImage imag;
            imag = ImageIO.read(is);
            Image image = imag;
            ImageIcon icon = new ImageIcon(image);
     
            this.libContent.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(FingerThread.class.getName()).log(Level.SEVERE, null, ex);
        }
 }
}
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel choixEmpreinte;
    private javax.swing.JPanel container;
    private javax.swing.JLabel datenaiss;
    private javax.swing.JButton enregButton;
    private javax.swing.JPanel gaugePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labanotherfinger;
    private javax.swing.JLabel labenreg;
    private javax.swing.JLabel labfingerone;
    private javax.swing.JLabel labident;
    private javax.swing.JLabel labmatchdatenaiss;
    private javax.swing.JLabel labmatchfp;
    private javax.swing.JLabel labmatchname;
    private javax.swing.JLabel labmatchtypat;
    private javax.swing.JLabel libanotherfinger;
    private javax.swing.JLabel libfingerone;
    private javax.swing.JFormattedTextField matriculeField;
    private javax.swing.JPanel menubar;
    private javax.swing.JLabel name;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel panCollabs;
    private javax.swing.JPanel panEmpreinte;
    private javax.swing.JPanel panEmpreintedigit;
    private javax.swing.JPanel panEnregistrement;
    private javax.swing.JPanel panIdentInfo;
    private javax.swing.JPanel panIdentification;
    private javax.swing.JPanel panInfoCollabs;
    private javax.swing.JComboBox<String> selectFinger;
    private javax.swing.JLabel typepat;
    // End of variables declaration//GEN-END:variables
}
